### ISSUE TITLE
something^^^

### ISSUE THREAD

**Issue by Allianzcortex** [yumendy/LibraryManagement#1]
不是太确定，看了一下代码～：

如果用`login_required`,那么可以在 `settings.py` 中加入 `LOGIN_URL`，就可以不用每次都传入参数了

还有 yumendy 觉得是用 bootstrap  css,jquery 文件好还是用 django_bootstrap3 好？后者可以用 `{% bootstrap_form form %} 来快速生成表单，但增加了记忆成本

**Comment by yumendy** [comment]
谢谢您~第一个问题的确是当时有点偷懒了。

第二个主要是想针对新人，目的也是为了让大家了解django，所以大家可以选择自己喜欢的前端框架。所以没有使用django_bootstrap3.

其实我一般写这类典型的应用喜欢使用类视图来写。

第一个问题我会尽快修复。再一次谢谢您~

如果有时间的话也欢迎您关注我的另外一个Django项目 https://github.com/yumendy/CommunityManagement

欢迎多交流^_^

**Comment by Allianzcortex** [comment]
突然觉得前端框架好闹心……还是完全手写比较通用，也更能定制～～

类视图指的是 generic view ? 额，一直感觉 `form.ModelForms` 做到了 less code ，类视图的话我还是一只用 views.\*  ⊙﹏⊙b汗 还是要学习呀

那么 CommunityManagement 可以在本地启动吗？加上一个 'pip freeze > requirements.txt` 就更棒了！！
